#!/usr/bin/env python3
"""
F5 report generator: scan every lesson JSON and emit a translation-coverage report
so the backfill can be scheduled as its own job. Reports two things:

  1. For each non-English locale that appears anywhere, which lessons are MISSING it
     (learner silently gets English — now flagged in-app, but the content still needs
     authoring/translating).
  2. Every translated story variant that LACKS `##`/`###` headings — those regress to
     the single-card view instead of the scroll-synced layout, in that locale only.

Usage:  python scripts/translation_coverage_report.py [--out PATH]
Writes Markdown to TRANSLATION_COVERAGE_REPORT.md at the repo root by default.
"""
import argparse
import glob
import json
import os
import re

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LESSONS_GLOB = os.path.join(REPO, "backend", "lessons", "**", "*.json")
HEADING_RE = re.compile(r"^\s{0,3}#{2,3}\s", re.MULTILINE)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(REPO, "TRANSLATION_COVERAGE_REPORT.md"))
    args = ap.parse_args()

    lessons = []  # (lesson_id, track, story_variants)
    for path in glob.glob(LESSONS_GLOB, recursive=True):
        try:
            d = json.load(open(path, encoding="utf-8"))
        except Exception:
            continue
        sv = d.get("story_variants")
        if not isinstance(sv, dict) or "en" not in sv:
            continue
        lid = d.get("id") or os.path.splitext(os.path.basename(path))[0]
        lessons.append((lid, d.get("track", "?"), sv))

    all_locales = sorted({l for _, _, sv in lessons for l in sv if l != "en"})
    total = len(lessons)

    # 1. Missing-locale coverage.
    missing = {loc: sorted(lid for lid, _, sv in lessons if loc not in sv) for loc in all_locales}
    # 2. Translated variants lacking headings.
    heading_gaps = []  # (lesson_id, locale)
    for lid, _, sv in lessons:
        for loc, text in sv.items():
            if loc == "en" or not isinstance(text, str) or not text.strip():
                continue
            if not HEADING_RE.search(text):
                heading_gaps.append((lid, loc))

    lines = []
    lines.append("# Translation Coverage Report")
    lines.append("")
    lines.append(f"English lessons scanned: **{total}**. Non-English locales present: "
                 f"{', '.join(all_locales) or '(none)'}.")
    lines.append("")
    lines.append("Generated by `scripts/translation_coverage_report.py`. Regenerate after any "
                 "translation backfill. The app now flags the silent-fallback case at runtime "
                 "(F5); this report scopes the backfill work.")
    lines.append("")
    lines.append("## 1. Coverage by locale")
    lines.append("")
    lines.append("| Locale | Covered | Missing | Coverage |")
    lines.append("|--------|--------:|--------:|---------:|")
    for loc in all_locales:
        miss = len(missing[loc])
        cov = total - miss
        pct = f"{100*cov/total:.0f}%" if total else "—"
        lines.append(f"| {loc} | {cov} | {miss} | {pct} |")
    lines.append("")
    lines.append("## 2. Lessons missing each locale")
    lines.append("")
    for loc in all_locales:
        lines.append(f"### {loc} — {len(missing[loc])} missing")
        lines.append("")
        if missing[loc]:
            lines.append(", ".join(f"`{lid}`" for lid in missing[loc]))
        else:
            lines.append("_All lessons covered._")
        lines.append("")
    lines.append("## 3. Translated variants lacking `##`/`###` headings")
    lines.append("")
    lines.append("These render as a single card (not the scroll-synced layout) in that locale.")
    lines.append("")
    if heading_gaps:
        lines.append("| Lesson | Locale |")
        lines.append("|--------|--------|")
        for lid, loc in sorted(heading_gaps):
            lines.append(f"| `{lid}` | {loc} |")
    else:
        lines.append("_None — every translated variant has headings._")
    lines.append("")

    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Wrote {args.out}: {total} lessons, {len(all_locales)} locales, "
          f"{sum(len(v) for v in missing.values())} missing-locale rows, "
          f"{len(heading_gaps)} heading-gap variants.")


if __name__ == "__main__":
    main()
