"""
Knowledge graph seed data for PyMasters.
~300 concepts across 10 categories and ~213 edges defining prerequisite relationships.
"""

import sqlite3

# ---------------------------------------------------------------------------
# CONCEPTS  (id, name, category, difficulty, description)
# ---------------------------------------------------------------------------

CONCEPTS = [
    # ── python_core (~60) ──────────────────────────────────────────────────
    ("variables", "Variables", "python_core", 1, "Storing and naming values in Python"),
    ("data_types", "Data Types", "python_core", 1, "Integers, floats, strings, booleans and None"),
    ("type_conversion", "Type Conversion", "python_core", 1, "Converting between data types with int(), str(), float()"),
    ("operators", "Operators", "python_core", 1, "Arithmetic, comparison, logical and assignment operators"),
    ("string_basics", "String Basics", "python_core", 1, "Creating and indexing strings"),
    ("string_methods", "String Methods", "python_core", 1, "Common string operations like split, join, strip, replace"),
    ("string_formatting", "String Formatting", "python_core", 1, "f-strings, format() and % formatting"),
    ("conditionals", "Conditionals", "python_core", 1, "if, elif, else branching logic"),
    ("boolean_logic", "Boolean Logic", "python_core", 1, "and, or, not and truthiness rules"),
    ("for_loops", "For Loops", "python_core", 1, "Iterating over sequences with for"),
    ("while_loops", "While Loops", "python_core", 1, "Repeating code with while conditions"),
    ("loop_control", "Loop Control", "python_core", 1, "break, continue and else clauses in loops"),
    ("lists", "Lists", "python_core", 1, "Creating and using mutable ordered sequences"),
    ("list_methods", "List Methods", "python_core", 1, "append, extend, insert, remove, sort and more"),
    ("list_slicing", "List Slicing", "python_core", 1, "Extracting sublists with slice notation"),
    ("tuples", "Tuples", "python_core", 1, "Immutable ordered sequences"),
    ("dictionaries", "Dictionaries", "python_core", 2, "Key-value mappings for fast lookup"),
    ("dict_methods", "Dictionary Methods", "python_core", 2, "get, items, keys, values, update and setdefault"),
    ("sets", "Sets", "python_core", 2, "Unordered collections of unique elements"),
    ("nested_structures", "Nested Structures", "python_core", 2, "Lists of dicts, dicts of lists and complex nesting"),
    ("functions_basics", "Functions Basics", "python_core", 2, "Defining and calling reusable functions with def"),
    ("function_arguments", "Function Arguments", "python_core", 2, "Positional, keyword, default and *args/**kwargs"),
    ("return_values", "Return Values", "python_core", 2, "Returning single and multiple values from functions"),
    ("scope", "Scope", "python_core", 2, "Local, enclosing, global and built-in scope (LEGB)"),
    ("closures", "Closures", "python_core", 3, "Functions that capture variables from enclosing scope"),
    ("lambda_functions", "Lambda Functions", "python_core", 2, "Anonymous one-expression functions"),
    ("list_comprehension", "List Comprehension", "python_core", 2, "Concise list creation with [expr for x in iterable]"),
    ("dict_comprehension", "Dict Comprehension", "python_core", 3, "Building dicts with {k: v for k, v in ...}"),
    ("set_comprehension", "Set Comprehension", "python_core", 3, "Building sets with {expr for x in iterable}"),
    ("generators", "Generators", "python_core", 3, "Lazy iterators using yield"),
    ("generator_expressions", "Generator Expressions", "python_core", 3, "Memory-efficient generator syntax with parentheses"),
    ("decorators", "Decorators", "python_core", 3, "Wrapping functions to extend behavior with @syntax"),
    ("decorator_patterns", "Decorator Patterns", "python_core", 4, "Parameterized decorators, stacking and class decorators"),
    ("classes_basics", "Classes Basics", "python_core", 2, "Defining classes, __init__ and instance attributes"),
    ("inheritance", "Inheritance", "python_core", 3, "Extending classes and method resolution order"),
    ("composition", "Composition", "python_core", 3, "Building complex objects by combining simpler ones"),
    ("magic_methods", "Magic Methods", "python_core", 3, "Dunder methods like __str__, __repr__, __len__"),
    ("class_methods", "Class Methods", "python_core", 3, "@classmethod, @staticmethod and their use cases"),
    ("properties", "Properties", "python_core", 3, "Managed attributes with @property"),
    ("abstract_classes", "Abstract Classes", "python_core", 4, "Enforcing interfaces with ABC"),
    ("design_patterns", "Design Patterns", "python_core", 4, "Singleton, factory, observer and strategy in Python"),
    ("context_managers", "Context Managers", "python_core", 3, "with statement and writing custom context managers"),
    ("error_handling", "Error Handling", "python_core", 2, "try, except, else, finally for catching exceptions"),
    ("custom_exceptions", "Custom Exceptions", "python_core", 3, "Defining your own exception classes"),
    ("file_reading", "File Reading", "python_core", 2, "Reading text and binary files with open()"),
    ("file_writing", "File Writing", "python_core", 2, "Writing and appending data to files"),
    ("modules_imports", "Modules and Imports", "python_core", 2, "Organizing code with modules and import statements"),
    ("type_hints", "Type Hints", "python_core", 3, "Adding type annotations for better code clarity"),
    ("dataclasses", "Dataclasses", "python_core", 3, "Auto-generated __init__, __repr__ with @dataclass"),
    ("async_basics", "Async Basics", "python_core", 4, "async/await fundamentals and event loops"),
    ("async_advanced", "Async Advanced", "python_core", 5, "Gathering tasks, semaphores and async generators"),
    ("threading", "Threading", "python_core", 4, "Concurrent execution with threads and the GIL"),
    ("multiprocessing", "Multiprocessing", "python_core", 4, "Parallel execution across CPU cores"),
    ("recursion", "Recursion", "python_core", 3, "Functions that call themselves to solve subproblems"),
    ("memoization", "Memoization", "python_core", 3, "Caching function results for repeated calls"),
    ("walrus_operator", "Walrus Operator", "python_core", 3, "Assignment expressions with :="),
    ("unpacking", "Unpacking", "python_core", 2, "Destructuring sequences and dicts with * and **"),
    ("iterators", "Iterators", "python_core", 3, "The iterator protocol: __iter__ and __next__"),
    ("metaclasses", "Metaclasses", "python_core", 5, "Classes that create classes"),

    # ── stdlib (~25) ───────────────────────────────────────────────────────
    ("pathlib", "Pathlib", "stdlib", 2, "Object-oriented filesystem paths"),
    ("datetime_module", "Datetime Module", "stdlib", 2, "Working with dates, times and timedeltas"),
    ("regex", "Regular Expressions", "stdlib", 3, "Pattern matching with the re module"),
    ("regex_advanced", "Advanced Regex", "stdlib", 4, "Lookaheads, groups, backreferences and flags"),
    ("json_module", "JSON Module", "stdlib", 2, "Serializing and deserializing JSON data"),
    ("csv_module", "CSV Module", "stdlib", 2, "Reading and writing CSV files"),
    ("collections_module", "Collections Module", "stdlib", 3, "Counter, defaultdict, namedtuple, deque and OrderedDict"),
    ("itertools_module", "Itertools Module", "stdlib", 3, "Efficient looping with chain, product, combinations"),
    ("functools_module", "Functools Module", "stdlib", 3, "Higher-order functions: partial, reduce, lru_cache"),
    ("os_module", "OS Module", "stdlib", 2, "Interacting with the operating system"),
    ("sys_module", "Sys Module", "stdlib", 2, "System-specific parameters and functions"),
    ("subprocess_module", "Subprocess Module", "stdlib", 3, "Running external commands from Python"),
    ("logging_module", "Logging Module", "stdlib", 3, "Structured logging with handlers and formatters"),
    ("argparse_module", "Argparse Module", "stdlib", 3, "Parsing command-line arguments"),
    ("sqlite3_module", "SQLite3 Module", "stdlib", 3, "Embedded SQL database access from Python"),
    ("unittest_module", "Unittest Module", "stdlib", 3, "Built-in test framework with TestCase"),
    ("typing_module", "Typing Module", "stdlib", 3, "Advanced type annotations: Optional, Union, Generic"),
    ("abc_module", "ABC Module", "stdlib", 3, "Abstract base classes for interface enforcement"),
    ("contextlib_module", "Contextlib Module", "stdlib", 3, "Utilities for context managers like contextmanager"),
    ("dataclasses_module", "Dataclasses Module", "stdlib", 3, "Field options, post_init and advanced dataclass usage"),
    ("enum_module", "Enum Module", "stdlib", 2, "Defining symbolic enumerations"),
    ("math_module", "Math Module", "stdlib", 1, "Mathematical functions and constants"),
    ("random_module", "Random Module", "stdlib", 2, "Generating pseudo-random numbers and selections"),
    ("secrets_module", "Secrets Module", "stdlib", 2, "Cryptographically strong random numbers"),
    ("hashlib_module", "Hashlib Module", "stdlib", 3, "Secure hash functions like SHA-256 and MD5"),

    # ── web_dev (~26) ──────────────────────────────────────────────────────
    ("http_fundamentals", "HTTP Fundamentals", "web_dev", 2, "Request/response cycle, methods, status codes"),
    ("rest_api", "REST API Design", "web_dev", 3, "RESTful resource design and conventions"),
    ("api_consumption", "API Consumption", "web_dev", 2, "Calling APIs with requests and httpx"),
    ("flask_basics", "Flask Basics", "web_dev", 3, "Routes, templates and a minimal Flask app"),
    ("flask_forms", "Flask Forms", "web_dev", 3, "Form handling and validation with WTForms"),
    ("flask_auth", "Flask Authentication", "web_dev", 4, "Login, sessions and Flask-Login"),
    ("django_basics", "Django Basics", "web_dev", 3, "Project structure, settings and the admin"),
    ("django_models", "Django Models", "web_dev", 3, "ORM model definitions, migrations and queries"),
    ("django_views", "Django Views", "web_dev", 3, "Function-based and class-based views"),
    ("django_forms", "Django Forms", "web_dev", 3, "ModelForms, validation and CSRF protection"),
    ("django_rest", "Django REST Framework", "web_dev", 4, "Serializers, viewsets and routers for DRF"),
    ("fastapi_basics", "FastAPI Basics", "web_dev", 3, "Path operations, automatic docs and Pydantic models"),
    ("fastapi_crud", "FastAPI CRUD", "web_dev", 3, "Building create-read-update-delete endpoints"),
    ("fastapi_auth", "FastAPI Auth", "web_dev", 4, "OAuth2 and JWT authentication in FastAPI"),
    ("html_css", "HTML & CSS", "web_dev", 2, "Structuring and styling web pages"),
    ("javascript_basics", "JavaScript Basics", "web_dev", 2, "Core JS syntax for front-end interactivity"),
    ("websockets", "WebSockets", "web_dev", 4, "Real-time bidirectional communication"),
    ("deployment", "Deployment", "web_dev", 4, "Deploying Python web apps to cloud platforms"),
    ("docker", "Docker for Web", "web_dev", 4, "Containerizing web applications"),
    ("sql_basics", "SQL Basics", "web_dev", 2, "SELECT, INSERT, UPDATE, DELETE and JOINs"),
    ("orm_concepts", "ORM Concepts", "web_dev", 3, "Object-relational mapping with SQLAlchemy"),
    ("api_design", "API Design Best Practices", "web_dev", 4, "Versioning, pagination, error handling for APIs"),
    ("authentication_concepts", "Authentication Concepts", "web_dev", 3, "Sessions, tokens, OAuth and JWT fundamentals"),
    ("web_security", "Web Security", "web_dev", 4, "XSS, CSRF, SQL injection and OWASP basics"),
    ("templating", "Templating", "web_dev", 2, "Jinja2 and Django template engines"),
    ("web_scraping", "Web Scraping", "web_dev", 3, "Extracting data from websites with BeautifulSoup"),

    # ── data_science (~13) ─────────────────────────────────────────────────
    ("numpy_basics", "NumPy Basics", "data_science", 2, "Arrays, indexing, broadcasting and vectorized ops"),
    ("numpy_linalg", "NumPy Linear Algebra", "data_science", 3, "Matrix operations, eigenvalues and decompositions"),
    ("pandas_basics", "Pandas Basics", "data_science", 2, "Series, DataFrames, indexing and selection"),
    ("pandas_grouping", "Pandas Grouping", "data_science", 3, "groupby, aggregation and pivot tables"),
    ("pandas_merging", "Pandas Merging", "data_science", 3, "merge, join, concat for combining DataFrames"),
    ("data_cleaning", "Data Cleaning", "data_science", 3, "Handling missing values, duplicates and outliers"),
    ("data_visualization", "Data Visualization", "data_science", 2, "Principles of effective visual communication"),
    ("matplotlib_basics", "Matplotlib Basics", "data_science", 2, "Line plots, bar charts, histograms and customization"),
    ("seaborn_basics", "Seaborn Basics", "data_science", 3, "Statistical plots with Seaborn"),
    ("statistics_basics", "Statistics Basics", "data_science", 2, "Mean, median, variance, distributions and hypothesis tests"),
    ("feature_engineering", "Feature Engineering", "data_science", 4, "Creating and transforming features for ML models"),
    ("data_pipelines", "Data Pipelines", "data_science", 4, "Automating data ingestion and transformation"),
    ("exploratory_analysis", "Exploratory Data Analysis", "data_science", 3, "Systematic investigation of datasets with visuals"),

    # ── ai_ml (~20) ────────────────────────────────────────────────────────
    ("ml_fundamentals", "ML Fundamentals", "ai_ml", 3, "Supervised, unsupervised and reinforcement learning overview"),
    ("ml_workflow", "ML Workflow", "ai_ml", 3, "End-to-end pipeline from data to deployment"),
    ("train_test_split", "Train-Test Split", "ai_ml", 3, "Splitting data for model validation"),
    ("linear_regression", "Linear Regression", "ai_ml", 3, "Predicting continuous values with a best-fit line"),
    ("logistic_regression", "Logistic Regression", "ai_ml", 3, "Binary classification with sigmoid function"),
    ("decision_trees", "Decision Trees", "ai_ml", 3, "Tree-based classification and regression"),
    ("random_forests", "Random Forests", "ai_ml", 4, "Ensemble of decision trees for robust predictions"),
    ("svm", "Support Vector Machines", "ai_ml", 4, "Finding optimal hyperplanes for classification"),
    ("knn", "K-Nearest Neighbors", "ai_ml", 3, "Classification by proximity in feature space"),
    ("naive_bayes", "Naive Bayes", "ai_ml", 3, "Probabilistic classifier using Bayes theorem"),
    ("clustering_kmeans", "K-Means Clustering", "ai_ml", 3, "Partitioning data into k groups"),
    ("clustering_advanced", "Advanced Clustering", "ai_ml", 4, "DBSCAN, hierarchical and spectral clustering"),
    ("dimensionality_reduction", "Dimensionality Reduction", "ai_ml", 4, "PCA, t-SNE and UMAP for feature reduction"),
    ("model_evaluation", "Model Evaluation", "ai_ml", 3, "Accuracy, precision, recall, F1, ROC-AUC metrics"),
    ("hyperparameter_tuning", "Hyperparameter Tuning", "ai_ml", 4, "Grid search, random search and Bayesian optimization"),
    ("sklearn_pipelines", "Scikit-learn Pipelines", "ai_ml", 4, "Chaining preprocessing and models in sklearn"),
    ("model_deployment", "Model Deployment", "ai_ml", 4, "Serving ML models via APIs and batch inference"),
    ("bias_variance", "Bias-Variance Tradeoff", "ai_ml", 3, "Understanding underfitting and overfitting"),
    ("ensemble_methods", "Ensemble Methods", "ai_ml", 4, "Bagging, boosting and stacking techniques"),
    ("gradient_boosting", "Gradient Boosting", "ai_ml", 4, "XGBoost, LightGBM and CatBoost"),

    # ── deep_learning (~25) ────────────────────────────────────────────────
    ("perceptron", "Perceptron", "deep_learning", 3, "Single-layer neural unit and linear decision boundary"),
    ("multilayer_network", "Multilayer Network", "deep_learning", 3, "Stacking layers to learn non-linear patterns"),
    ("activation_functions", "Activation Functions", "deep_learning", 3, "ReLU, sigmoid, tanh and softmax"),
    ("forward_pass", "Forward Pass", "deep_learning", 3, "Computing predictions through network layers"),
    ("loss_functions", "Loss Functions", "deep_learning", 3, "MSE, cross-entropy and custom loss functions"),
    ("backpropagation", "Backpropagation", "deep_learning", 4, "Computing gradients with the chain rule"),
    ("gradient_descent_dl", "Gradient Descent (DL)", "deep_learning", 4, "SGD, Adam, learning rate schedules"),
    ("regularization_dl", "Regularization (DL)", "deep_learning", 4, "Dropout, weight decay, batch normalization"),
    ("pytorch_basics", "PyTorch Basics", "deep_learning", 3, "Tensors, autograd and basic operations"),
    ("pytorch_training", "PyTorch Training Loop", "deep_learning", 4, "Datasets, DataLoaders and the training loop"),
    ("cnn_basics", "CNN Basics", "deep_learning", 4, "Convolutional layers, pooling and feature maps"),
    ("cnn_architectures", "CNN Architectures", "deep_learning", 4, "VGG, ResNet, Inception and EfficientNet"),
    ("image_classification", "Image Classification", "deep_learning", 4, "Building and training image classifiers"),
    ("transfer_learning", "Transfer Learning", "deep_learning", 4, "Fine-tuning pre-trained models for new tasks"),
    ("rnn_basics", "RNN Basics", "deep_learning", 4, "Recurrent neural networks for sequential data"),
    ("lstm_gru", "LSTM and GRU", "deep_learning", 4, "Gated recurrent units for long-range dependencies"),
    ("text_generation", "Text Generation", "deep_learning", 4, "Generating text with language models"),
    ("attention_mechanism", "Attention Mechanism", "deep_learning", 5, "Scaled dot-product and multi-head attention"),
    ("transformer_architecture", "Transformer Architecture", "deep_learning", 5, "Encoder-decoder architecture with self-attention"),
    ("bert_gpt", "BERT and GPT", "deep_learning", 5, "Pre-trained transformer models for NLP"),
    ("gan_basics", "GAN Basics", "deep_learning", 4, "Generator-discriminator adversarial training"),
    ("gan_image", "GAN Image Generation", "deep_learning", 5, "Generating realistic images with GANs"),
    ("autoencoders", "Autoencoders", "deep_learning", 4, "Encoder-decoder networks for representation learning"),
    ("model_optimization", "Model Optimization", "deep_learning", 5, "Quantization, pruning and knowledge distillation"),
    ("dl_project", "DL Capstone Project", "deep_learning", 5, "End-to-end deep learning project from data to deployment"),

    # ── devops (~14) ───────────────────────────────────────────────────────
    ("testing_fundamentals", "Testing Fundamentals", "devops", 2, "Why we test and types of tests"),
    ("pytest_basics", "Pytest Basics", "devops", 2, "Writing and running tests with pytest"),
    ("pytest_advanced", "Pytest Advanced", "devops", 3, "Fixtures, parametrize, mocking and plugins"),
    ("tdd", "Test-Driven Development", "devops", 3, "Red-green-refactor workflow"),
    ("ci_cd_basics", "CI/CD Basics", "devops", 3, "Continuous integration and delivery concepts"),
    ("ci_cd_python", "CI/CD for Python", "devops", 4, "GitHub Actions and pipelines for Python projects"),
    ("docker_basics", "Docker Basics", "devops", 3, "Images, containers, Dockerfile and docker run"),
    ("docker_compose", "Docker Compose", "devops", 4, "Multi-container orchestration with compose files"),
    ("packaging", "Python Packaging", "devops", 3, "setup.py, pyproject.toml and publishing to PyPI"),
    ("git_basics", "Git Basics", "devops", 1, "init, add, commit, push, pull and branching"),
    ("git_workflows", "Git Workflows", "devops", 3, "Feature branch, GitFlow and trunk-based development"),
    ("logging", "Logging Best Practices", "devops", 3, "Structured logging, levels and log aggregation"),
    ("code_quality", "Code Quality", "devops", 3, "Linting, formatting with black, ruff and mypy"),
    ("virtual_envs", "Virtual Environments", "devops", 1, "venv, pip and dependency isolation"),

    # ── automation (~11) ───────────────────────────────────────────────────
    ("file_automation", "File Automation", "automation", 2, "Batch renaming, moving and organizing files"),
    ("web_scraping_auto", "Web Scraping Automation", "automation", 3, "Automated data extraction from websites"),
    ("email_automation", "Email Automation", "automation", 3, "Sending emails programmatically with smtplib"),
    ("pdf_automation", "PDF Automation", "automation", 3, "Reading, merging and creating PDFs"),
    ("excel_automation", "Excel Automation", "automation", 3, "Reading and writing spreadsheets with openpyxl"),
    ("cli_tools", "CLI Tools", "automation", 3, "Building command-line applications with click/typer"),
    ("task_scheduling", "Task Scheduling", "automation", 3, "Scheduling scripts with cron and schedule library"),
    ("browser_automation", "Browser Automation", "automation", 3, "Controlling browsers with Selenium and Playwright"),
    ("api_automation", "API Automation", "automation", 3, "Automating workflows through REST API calls"),
    ("password_generation", "Password Generation", "automation", 2, "Generating secure passwords and tokens"),
    ("data_backup", "Data Backup Scripts", "automation", 3, "Automated file and database backup solutions"),

    # ── dsa (~20) ──────────────────────────────────────────────────────────
    ("big_o", "Big-O Notation", "dsa", 2, "Analyzing time and space complexity of algorithms"),
    ("arrays", "Arrays", "dsa", 2, "Contiguous memory sequences and basic operations"),
    ("linked_lists", "Linked Lists", "dsa", 3, "Node-based sequential data structures"),
    ("stacks", "Stacks", "dsa", 2, "LIFO data structure and its applications"),
    ("queues", "Queues", "dsa", 2, "FIFO data structure, deques and priority queues"),
    ("hash_tables", "Hash Tables", "dsa", 3, "Key-value storage with hashing and collision handling"),
    ("binary_trees", "Binary Trees", "dsa", 3, "Tree structure, traversals and properties"),
    ("bst", "Binary Search Trees", "dsa", 3, "Ordered trees for efficient search and insertion"),
    ("heaps", "Heaps", "dsa", 3, "Min-heaps, max-heaps and the heapq module"),
    ("graphs", "Graphs", "dsa", 4, "Vertices, edges, BFS and DFS"),
    ("graphs_advanced", "Advanced Graphs", "dsa", 4, "Dijkstra, Bellman-Ford and topological sort"),
    ("sorting_basic", "Basic Sorting", "dsa", 2, "Bubble sort, selection sort and insertion sort"),
    ("sorting_advanced", "Advanced Sorting", "dsa", 3, "Merge sort, quicksort and counting sort"),
    ("binary_search", "Binary Search", "dsa", 2, "Efficiently finding elements in sorted sequences"),
    ("recursion_dsa", "Recursion in DSA", "dsa", 3, "Recursive problem solving and call stacks"),
    ("dynamic_programming", "Dynamic Programming", "dsa", 4, "Optimal substructure and overlapping subproblems"),
    ("greedy_algorithms", "Greedy Algorithms", "dsa", 4, "Making locally optimal choices for global solutions"),
    ("string_algorithms", "String Algorithms", "dsa", 4, "KMP, Rabin-Karp and trie-based matching"),
    ("sliding_window", "Sliding Window", "dsa", 3, "Fixed and variable window techniques for subarrays"),
    ("two_pointers", "Two Pointers", "dsa", 3, "Using two indices to solve array problems efficiently"),

    # ── ai_dev (~20) ───────────────────────────────────────────────────────
    ("what_is_ai", "What Is AI", "ai_dev", 1, "Overview of artificial intelligence and its branches"),
    ("prompt_engineering", "Prompt Engineering", "ai_dev", 2, "Crafting effective prompts for large language models"),
    ("prompt_advanced", "Advanced Prompting", "ai_dev", 3, "Chain-of-thought, few-shot and system prompts"),
    ("llm_concepts", "LLM Concepts", "ai_dev", 3, "Tokens, context windows, temperature and sampling"),
    ("openai_api", "OpenAI API", "ai_dev", 3, "Using GPT models via the OpenAI Python client"),
    ("anthropic_api", "Anthropic API", "ai_dev", 3, "Using Claude models via the Anthropic Python client"),
    ("langchain_basics", "LangChain Basics", "ai_dev", 3, "Chains, prompts and output parsers in LangChain"),
    ("langchain_agents", "LangChain Agents", "ai_dev", 4, "Tool-using agents and agent executors"),
    ("rag", "RAG", "ai_dev", 4, "Retrieval-augmented generation for grounded answers"),
    ("embeddings", "Embeddings", "ai_dev", 3, "Vector representations of text for similarity search"),
    ("vector_databases", "Vector Databases", "ai_dev", 4, "Storing and querying embeddings with Pinecone, Chroma"),
    ("chatbot_building", "Chatbot Building", "ai_dev", 3, "Designing conversational AI applications"),
    ("ai_code_assistants", "AI Code Assistants", "ai_dev", 2, "Using Copilot, Claude Code and Cursor effectively"),
    ("structured_output", "Structured Output", "ai_dev", 3, "Getting JSON and typed responses from LLMs"),
    ("multimodal_ai", "Multimodal AI", "ai_dev", 4, "Processing images, audio and text with AI models"),
    ("ai_safety", "AI Safety", "ai_dev", 3, "Responsible AI, guardrails and content filtering"),
    ("fine_tuning", "Fine-Tuning", "ai_dev", 5, "Training custom models on domain-specific data"),
    ("ai_deployment", "AI Deployment", "ai_dev", 4, "Deploying AI applications to production"),
    ("ai_evaluation", "AI Evaluation", "ai_dev", 4, "Benchmarking and evaluating LLM outputs"),
    ("agent_frameworks", "Agent Frameworks", "ai_dev", 4, "Building autonomous AI agents with tool use"),
]

# ---------------------------------------------------------------------------
# CONCEPT_EDGES  (from_concept, to_concept, relationship, weight)
# ---------------------------------------------------------------------------

CONCEPT_EDGES = [
    # ── python_core chain ──────────────────────────────────────────────────
    ("variables", "data_types", "requires", 1.0),
    ("data_types", "type_conversion", "requires", 1.0),
    ("data_types", "operators", "requires", 1.0),
    ("data_types", "string_basics", "requires", 1.0),
    ("string_basics", "string_methods", "requires", 1.0),
    ("string_basics", "string_formatting", "requires", 1.0),
    ("operators", "conditionals", "requires", 1.0),
    ("conditionals", "boolean_logic", "requires", 1.0),
    ("conditionals", "for_loops", "requires", 1.0),
    ("conditionals", "while_loops", "requires", 1.0),
    ("for_loops", "loop_control", "requires", 1.0),
    ("while_loops", "loop_control", "recommends", 0.7),
    ("data_types", "lists", "requires", 1.0),
    ("lists", "list_methods", "requires", 1.0),
    ("lists", "list_slicing", "requires", 1.0),
    ("lists", "tuples", "recommends", 0.7),
    ("lists", "dictionaries", "requires", 1.0),
    ("dictionaries", "dict_methods", "requires", 1.0),
    ("lists", "sets", "recommends", 0.7),
    ("dictionaries", "nested_structures", "requires", 1.0),
    ("lists", "nested_structures", "requires", 1.0),
    ("for_loops", "functions_basics", "requires", 1.0),
    ("functions_basics", "function_arguments", "requires", 1.0),
    ("functions_basics", "return_values", "requires", 1.0),
    ("functions_basics", "scope", "requires", 1.0),
    ("scope", "closures", "requires", 1.0),
    ("functions_basics", "lambda_functions", "requires", 1.0),
    ("for_loops", "list_comprehension", "requires", 1.0),
    ("lists", "list_comprehension", "requires", 1.0),
    ("dictionaries", "dict_comprehension", "requires", 1.0),
    ("list_comprehension", "dict_comprehension", "recommends", 0.7),
    ("list_comprehension", "set_comprehension", "recommends", 0.7),
    ("functions_basics", "generators", "requires", 1.0),
    ("iterators", "generators", "requires", 1.0),
    ("generators", "generator_expressions", "requires", 1.0),
    ("closures", "decorators", "requires", 1.0),
    ("functions_basics", "decorators", "requires", 1.0),
    ("decorators", "decorator_patterns", "requires", 1.0),
    ("functions_basics", "classes_basics", "requires", 1.0),
    ("classes_basics", "inheritance", "requires", 1.0),
    ("classes_basics", "composition", "requires", 1.0),
    ("classes_basics", "magic_methods", "requires", 1.0),
    ("classes_basics", "class_methods", "requires", 1.0),
    ("classes_basics", "properties", "requires", 1.0),
    ("inheritance", "abstract_classes", "requires", 1.0),
    ("abstract_classes", "design_patterns", "recommends", 0.7),
    ("composition", "design_patterns", "recommends", 0.7),
    ("functions_basics", "context_managers", "requires", 1.0),
    ("conditionals", "error_handling", "requires", 1.0),
    ("error_handling", "custom_exceptions", "requires", 1.0),
    ("classes_basics", "custom_exceptions", "requires", 1.0),
    ("file_reading", "file_writing", "recommends", 0.7),
    ("error_handling", "file_reading", "requires", 1.0),
    ("functions_basics", "modules_imports", "requires", 1.0),
    ("functions_basics", "type_hints", "recommends", 0.7),
    ("type_hints", "dataclasses", "requires", 1.0),
    ("classes_basics", "dataclasses", "requires", 1.0),
    ("functions_basics", "async_basics", "requires", 1.0),
    ("async_basics", "async_advanced", "requires", 1.0),
    ("functions_basics", "threading", "requires", 1.0),
    ("functions_basics", "multiprocessing", "requires", 1.0),
    ("functions_basics", "recursion", "requires", 1.0),
    ("recursion", "memoization", "requires", 1.0),
    ("conditionals", "walrus_operator", "recommends", 0.7),
    ("tuples", "unpacking", "requires", 1.0),
    ("lists", "unpacking", "requires", 1.0),
    ("for_loops", "iterators", "requires", 1.0),
    ("classes_basics", "iterators", "requires", 1.0),
    ("classes_basics", "metaclasses", "requires", 1.0),
    ("inheritance", "metaclasses", "requires", 1.0),

    # ── stdlib dependencies ────────────────────────────────────────────────
    ("file_reading", "pathlib", "recommends", 0.7),
    ("modules_imports", "pathlib", "requires", 1.0),
    ("modules_imports", "datetime_module", "requires", 1.0),
    ("string_methods", "regex", "requires", 1.0),
    ("regex", "regex_advanced", "requires", 1.0),
    ("dictionaries", "json_module", "requires", 1.0),
    ("file_reading", "json_module", "requires", 1.0),
    ("file_reading", "csv_module", "requires", 1.0),
    ("dictionaries", "collections_module", "requires", 1.0),
    ("for_loops", "itertools_module", "requires", 1.0),
    ("functions_basics", "functools_module", "requires", 1.0),
    ("lambda_functions", "functools_module", "recommends", 0.7),
    ("modules_imports", "os_module", "requires", 1.0),
    ("modules_imports", "sys_module", "requires", 1.0),
    ("os_module", "subprocess_module", "requires", 1.0),
    ("error_handling", "logging_module", "requires", 1.0),
    ("function_arguments", "argparse_module", "requires", 1.0),
    ("sql_basics", "sqlite3_module", "requires", 1.0),
    ("functions_basics", "unittest_module", "requires", 1.0),
    ("type_hints", "typing_module", "requires", 1.0),
    ("abstract_classes", "abc_module", "requires", 1.0),
    ("context_managers", "contextlib_module", "requires", 1.0),
    ("dataclasses", "dataclasses_module", "requires", 1.0),
    ("classes_basics", "enum_module", "requires", 1.0),
    ("operators", "math_module", "recommends", 0.7),
    ("modules_imports", "random_module", "requires", 1.0),
    ("random_module", "secrets_module", "recommends", 0.7),
    ("string_basics", "hashlib_module", "recommends", 0.7),
    ("modules_imports", "hashlib_module", "requires", 1.0),

    # ── web_dev progression ────────────────────────────────────────────────
    ("functions_basics", "http_fundamentals", "requires", 1.0),
    ("http_fundamentals", "rest_api", "requires", 1.0),
    ("http_fundamentals", "api_consumption", "requires", 1.0),
    ("rest_api", "api_design", "requires", 1.0),
    ("http_fundamentals", "flask_basics", "requires", 1.0),
    ("flask_basics", "flask_forms", "requires", 1.0),
    ("flask_forms", "flask_auth", "requires", 1.0),
    ("flask_basics", "templating", "recommends", 0.7),
    ("http_fundamentals", "django_basics", "requires", 1.0),
    ("django_basics", "django_models", "requires", 1.0),
    ("django_models", "django_views", "requires", 1.0),
    ("django_views", "django_forms", "requires", 1.0),
    ("django_models", "django_rest", "requires", 1.0),
    ("rest_api", "django_rest", "requires", 1.0),
    ("http_fundamentals", "fastapi_basics", "requires", 1.0),
    ("type_hints", "fastapi_basics", "requires", 1.0),
    ("fastapi_basics", "fastapi_crud", "requires", 1.0),
    ("fastapi_crud", "fastapi_auth", "requires", 1.0),
    ("authentication_concepts", "fastapi_auth", "requires", 1.0),
    ("authentication_concepts", "flask_auth", "requires", 1.0),
    ("html_css", "templating", "requires", 1.0),
    ("html_css", "javascript_basics", "recommends", 0.7),
    ("http_fundamentals", "websockets", "requires", 1.0),
    ("async_basics", "websockets", "recommends", 0.7),
    ("http_fundamentals", "deployment", "requires", 1.0),
    ("docker", "deployment", "recommends", 0.7),
    ("dictionaries", "sql_basics", "recommends", 0.7),
    ("sql_basics", "orm_concepts", "requires", 1.0),
    ("classes_basics", "orm_concepts", "requires", 1.0),
    ("http_fundamentals", "authentication_concepts", "requires", 1.0),
    ("authentication_concepts", "web_security", "requires", 1.0),
    ("api_consumption", "web_scraping", "requires", 1.0),
    ("html_css", "web_scraping", "requires", 1.0),

    # ── data_science → ml → dl chain ──────────────────────────────────────
    ("lists", "numpy_basics", "requires", 1.0),
    ("for_loops", "numpy_basics", "requires", 1.0),
    ("numpy_basics", "numpy_linalg", "requires", 1.0),
    ("numpy_basics", "pandas_basics", "requires", 1.0),
    ("pandas_basics", "pandas_grouping", "requires", 1.0),
    ("pandas_basics", "pandas_merging", "requires", 1.0),
    ("pandas_basics", "data_cleaning", "requires", 1.0),
    ("data_cleaning", "exploratory_analysis", "requires", 1.0),
    ("matplotlib_basics", "exploratory_analysis", "requires", 1.0),
    ("numpy_basics", "matplotlib_basics", "requires", 1.0),
    ("numpy_basics", "data_visualization", "recommends", 0.7),
    ("matplotlib_basics", "seaborn_basics", "requires", 1.0),
    ("pandas_basics", "seaborn_basics", "recommends", 0.7),
    ("numpy_basics", "statistics_basics", "requires", 1.0),
    ("pandas_basics", "feature_engineering", "requires", 1.0),
    ("statistics_basics", "feature_engineering", "recommends", 0.7),
    ("pandas_basics", "data_pipelines", "requires", 1.0),

    # ml chain
    ("statistics_basics", "ml_fundamentals", "requires", 1.0),
    ("numpy_basics", "ml_fundamentals", "requires", 1.0),
    ("ml_fundamentals", "ml_workflow", "requires", 1.0),
    ("ml_workflow", "train_test_split", "requires", 1.0),
    ("train_test_split", "linear_regression", "requires", 1.0),
    ("linear_regression", "logistic_regression", "requires", 1.0),
    ("ml_fundamentals", "decision_trees", "requires", 1.0),
    ("decision_trees", "random_forests", "requires", 1.0),
    ("ml_fundamentals", "svm", "requires", 1.0),
    ("ml_fundamentals", "knn", "requires", 1.0),
    ("ml_fundamentals", "naive_bayes", "requires", 1.0),
    ("ml_fundamentals", "clustering_kmeans", "requires", 1.0),
    ("clustering_kmeans", "clustering_advanced", "requires", 1.0),
    ("statistics_basics", "dimensionality_reduction", "requires", 1.0),
    ("numpy_linalg", "dimensionality_reduction", "recommends", 0.7),
    ("train_test_split", "model_evaluation", "requires", 1.0),
    ("model_evaluation", "hyperparameter_tuning", "requires", 1.0),
    ("ml_workflow", "sklearn_pipelines", "requires", 1.0),
    ("hyperparameter_tuning", "sklearn_pipelines", "recommends", 0.7),
    ("ml_workflow", "model_deployment", "requires", 1.0),
    ("ml_fundamentals", "bias_variance", "requires", 1.0),
    ("random_forests", "ensemble_methods", "requires", 1.0),
    ("ensemble_methods", "gradient_boosting", "requires", 1.0),

    # dl chain
    ("linear_regression", "perceptron", "requires", 1.0),
    ("numpy_basics", "perceptron", "requires", 1.0),
    ("perceptron", "multilayer_network", "requires", 1.0),
    ("perceptron", "activation_functions", "requires", 1.0),
    ("multilayer_network", "forward_pass", "requires", 1.0),
    ("activation_functions", "forward_pass", "requires", 1.0),
    ("forward_pass", "loss_functions", "requires", 1.0),
    ("loss_functions", "backpropagation", "requires", 1.0),
    ("backpropagation", "gradient_descent_dl", "requires", 1.0),
    ("gradient_descent_dl", "regularization_dl", "requires", 1.0),
    ("numpy_basics", "pytorch_basics", "requires", 1.0),
    ("multilayer_network", "pytorch_basics", "recommends", 0.7),
    ("pytorch_basics", "pytorch_training", "requires", 1.0),
    ("backpropagation", "pytorch_training", "requires", 1.0),
    ("pytorch_training", "cnn_basics", "requires", 1.0),
    ("cnn_basics", "cnn_architectures", "requires", 1.0),
    ("cnn_basics", "image_classification", "requires", 1.0),
    ("cnn_architectures", "transfer_learning", "requires", 1.0),
    ("pytorch_training", "rnn_basics", "requires", 1.0),
    ("rnn_basics", "lstm_gru", "requires", 1.0),
    ("lstm_gru", "text_generation", "requires", 1.0),
    ("lstm_gru", "attention_mechanism", "requires", 1.0),
    ("attention_mechanism", "transformer_architecture", "requires", 1.0),
    ("transformer_architecture", "bert_gpt", "requires", 1.0),
    ("pytorch_training", "gan_basics", "requires", 1.0),
    ("gan_basics", "gan_image", "requires", 1.0),
    ("pytorch_training", "autoencoders", "requires", 1.0),
    ("pytorch_training", "model_optimization", "requires", 1.0),
    ("transfer_learning", "dl_project", "recommends", 0.7),
    ("pytorch_training", "dl_project", "requires", 1.0),

    # ── dsa progression ────────────────────────────────────────────────────
    ("functions_basics", "big_o", "requires", 1.0),
    ("lists", "arrays", "requires", 1.0),
    ("big_o", "arrays", "requires", 1.0),
    ("arrays", "linked_lists", "requires", 1.0),
    ("arrays", "stacks", "requires", 1.0),
    ("arrays", "queues", "requires", 1.0),
    ("dictionaries", "hash_tables", "requires", 1.0),
    ("arrays", "hash_tables", "requires", 1.0),
    ("linked_lists", "binary_trees", "requires", 1.0),
    ("binary_trees", "bst", "requires", 1.0),
    ("binary_trees", "heaps", "requires", 1.0),
    ("arrays", "graphs", "requires", 1.0),
    ("queues", "graphs", "recommends", 0.7),
    ("graphs", "graphs_advanced", "requires", 1.0),
    ("arrays", "sorting_basic", "requires", 1.0),
    ("sorting_basic", "sorting_advanced", "requires", 1.0),
    ("arrays", "binary_search", "requires", 1.0),
    ("recursion", "recursion_dsa", "requires", 1.0),
    ("recursion_dsa", "dynamic_programming", "requires", 1.0),
    ("arrays", "dynamic_programming", "requires", 1.0),
    ("big_o", "greedy_algorithms", "requires", 1.0),
    ("arrays", "greedy_algorithms", "recommends", 0.7),
    ("string_methods", "string_algorithms", "requires", 1.0),
    ("arrays", "string_algorithms", "requires", 1.0),
    ("arrays", "sliding_window", "requires", 1.0),
    ("for_loops", "sliding_window", "requires", 1.0),
    ("arrays", "two_pointers", "requires", 1.0),
    ("binary_search", "two_pointers", "recommends", 0.7),

    # ── devops progression ─────────────────────────────────────────────────
    ("functions_basics", "testing_fundamentals", "requires", 1.0),
    ("testing_fundamentals", "pytest_basics", "requires", 1.0),
    ("pytest_basics", "pytest_advanced", "requires", 1.0),
    ("pytest_basics", "tdd", "requires", 1.0),
    ("git_basics", "ci_cd_basics", "requires", 1.0),
    ("ci_cd_basics", "ci_cd_python", "requires", 1.0),
    ("pytest_basics", "ci_cd_python", "recommends", 0.7),
    ("ci_cd_basics", "docker_basics", "recommends", 0.7),
    ("docker_basics", "docker_compose", "requires", 1.0),
    ("modules_imports", "packaging", "requires", 1.0),
    ("git_basics", "git_workflows", "requires", 1.0),
    ("logging_module", "logging", "requires", 1.0),
    ("modules_imports", "code_quality", "requires", 1.0),
    ("modules_imports", "virtual_envs", "requires", 1.0),

    # ── automation progression ─────────────────────────────────────────────
    ("pathlib", "file_automation", "requires", 1.0),
    ("file_reading", "file_automation", "requires", 1.0),
    ("web_scraping", "web_scraping_auto", "requires", 1.0),
    ("file_automation", "email_automation", "recommends", 0.7),
    ("file_reading", "pdf_automation", "requires", 1.0),
    ("file_reading", "excel_automation", "requires", 1.0),
    ("argparse_module", "cli_tools", "requires", 1.0),
    ("functions_basics", "task_scheduling", "requires", 1.0),
    ("web_scraping", "browser_automation", "requires", 1.0),
    ("api_consumption", "api_automation", "requires", 1.0),
    ("secrets_module", "password_generation", "requires", 1.0),
    ("random_module", "password_generation", "recommends", 0.7),
    ("file_automation", "data_backup", "requires", 1.0),

    # ── ai_dev progression ─────────────────────────────────────────────────
    ("what_is_ai", "prompt_engineering", "requires", 1.0),
    ("prompt_engineering", "prompt_advanced", "requires", 1.0),
    ("prompt_engineering", "llm_concepts", "requires", 1.0),
    ("llm_concepts", "openai_api", "requires", 1.0),
    ("api_consumption", "openai_api", "requires", 1.0),
    ("llm_concepts", "anthropic_api", "requires", 1.0),
    ("api_consumption", "anthropic_api", "requires", 1.0),
    ("openai_api", "langchain_basics", "requires", 1.0),
    ("langchain_basics", "langchain_agents", "requires", 1.0),
    ("langchain_basics", "rag", "requires", 1.0),
    ("embeddings", "rag", "requires", 1.0),
    ("llm_concepts", "embeddings", "requires", 1.0),
    ("embeddings", "vector_databases", "requires", 1.0),
    ("openai_api", "chatbot_building", "requires", 1.0),
    ("prompt_engineering", "ai_code_assistants", "recommends", 0.7),
    ("openai_api", "structured_output", "requires", 1.0),
    ("llm_concepts", "multimodal_ai", "requires", 1.0),
    ("prompt_engineering", "ai_safety", "requires", 1.0),
    ("openai_api", "fine_tuning", "requires", 1.0),
    ("ml_workflow", "fine_tuning", "recommends", 0.7),
    ("openai_api", "ai_deployment", "requires", 1.0),
    ("deployment", "ai_deployment", "recommends", 0.7),
    ("prompt_advanced", "ai_evaluation", "requires", 1.0),
    ("langchain_agents", "agent_frameworks", "requires", 1.0),

    # ── cross-domain edges ─────────────────────────────────────────────────
    ("docker_basics", "docker", "related_to", 0.3),
    ("sqlite3_module", "sql_basics", "related_to", 0.3),
    ("functools_module", "memoization", "related_to", 0.3),
    ("logging_module", "error_handling", "related_to", 0.3),
    ("unittest_module", "testing_fundamentals", "related_to", 0.3),
    ("model_deployment", "ai_deployment", "related_to", 0.3),
    ("feature_engineering", "sklearn_pipelines", "related_to", 0.3),
    ("bert_gpt", "llm_concepts", "related_to", 0.3),
    ("transformer_architecture", "attention_mechanism", "related_to", 0.3),
    ("web_scraping", "web_scraping_auto", "related_to", 0.3),
    ("json_module", "api_consumption", "related_to", 0.3),
    ("decorators", "flask_basics", "related_to", 0.3),
    ("async_basics", "fastapi_basics", "related_to", 0.3),
    ("dataclasses", "fastapi_basics", "related_to", 0.3),
]


# ---------------------------------------------------------------------------
# Seed function
# ---------------------------------------------------------------------------

def seed_concepts(db_path: str):
    """Insert all concepts and edges into the SQLite database."""
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    cursor.executemany(
        "INSERT OR IGNORE INTO concepts (id, name, category, difficulty, description) VALUES (?, ?, ?, ?, ?)",
        CONCEPTS,
    )
    cursor.executemany(
        "INSERT OR IGNORE INTO concept_edges (from_concept, to_concept, relationship, weight) VALUES (?, ?, ?, ?)",
        CONCEPT_EDGES,
    )
    conn.commit()
    conn.close()
    print(f"Seeded {len(CONCEPTS)} concepts and {len(CONCEPT_EDGES)} edges")
