"""Cross-pollination between Homie and PyMasters.

Creates GitHub issues that link discoveries between the two products:
1. PyMasters lesson about a technique -> Homie issue suggesting integration
2. Homie capability added -> PyMasters issue suggesting a tutorial
"""

import json
import subprocess

from pipeline.config import (
    HOMIE_REPO,
    PYMASTERS_REPO,
    RELEVANCE_THRESHOLD_HOMIE,
    RELEVANCE_THRESHOLD_PYMASTERS,
)
from pipeline.utils.logger import get_logger

log = get_logger("actor.cross_pollinate")


def _gh(*args: str, timeout: int = 30) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["gh", *args],
        capture_output=True,
        text=True,
        timeout=timeout,
    )


def _ensure_label(repo: str) -> None:
    _gh(
        "label", "create", "pipeline-generated",
        "--repo", repo,
        "--color", "0E8A16",
        "--description", "Auto-generated by AI pipeline",
        "--force",
    )


def _get_existing_titles(repo: str) -> set[str]:
    titles: set[str] = set()
    try:
        result = _gh(
            "issue", "list",
            "--repo", repo,
            "--label", "pipeline-generated",
            "--state", "all",
            "--limit", "100",
            "--json", "title",
        )
        if result.returncode == 0:
            for entry in json.loads(result.stdout):
                titles.add(entry["title"])
    except Exception as exc:
        log.warning(f"Could not fetch existing issues for {repo}: {exc}")
    return titles


def _create_homie_issue_from_pymasters(item: dict, existing: set[str]) -> dict | None:
    """When a PyMasters-relevant item is found, suggest Homie integration."""
    title = f"[Cross-pollinate] Integrate technique from: {item.get('title', 'Unknown')[:80]}"
    if title in existing:
        log.info(f"Skipping duplicate cross-pollination issue: {title}")
        return None

    body = f"""## Cross-pollination: PyMasters -> Homie

**Source:** {item.get('source', 'unknown')}
**Original:** [{item.get('title', '')}]({item.get('url', '')})
**PyMasters Score:** {item.get('pymasters_score', 0)}/10
**Homie Score:** {item.get('homie_score', 0)}/10

### Context
This item scored high for PyMasters content. It may also be applicable as a Homie feature
or plugin. This issue is a suggestion to evaluate whether the technique can be integrated
into Homie's local-first architecture.

### Opportunity
{item.get('opportunity', 'N/A')}

### Description
{item.get('description', 'N/A')[:500]}

### Suggested Next Steps
- Review the technique for local applicability (no cloud dependency)
- Check resource requirements for desktop and mobile targets
- If feasible, create a Homie plugin or core feature enhancement

---
*Cross-pollination issue created by the PyMasters AI Intelligence Pipeline.*
"""

    try:
        _ensure_label(HOMIE_REPO)
        result = _gh(
            "issue", "create",
            "--repo", HOMIE_REPO,
            "--title", title,
            "--body", body,
            "--label", "pipeline-generated",
        )
        if result.returncode == 0:
            url = result.stdout.strip()
            log.info(f"Created cross-pollination issue (Homie): {url}")
            return {"title": title, "url": url, "type": "cross_pymasters_to_homie", "item": item}
        else:
            log.error(f"Failed to create Homie cross-pollination issue: {result.stderr}")
    except Exception as exc:
        log.error(f"Error creating cross-pollination issue: {exc}")

    return None


def _create_pymasters_issue_from_homie(item: dict, existing: set[str]) -> dict | None:
    """When a Homie-relevant item is found, suggest a PyMasters tutorial."""
    title = f"[Cross-pollinate] Tutorial idea from Homie: {item.get('title', 'Unknown')[:80]}"
    if title in existing:
        log.info(f"Skipping duplicate cross-pollination issue: {title}")
        return None

    body = f"""## Cross-pollination: Homie -> PyMasters

**Source:** {item.get('source', 'unknown')}
**Original:** [{item.get('title', '')}]({item.get('url', '')})
**Homie Score:** {item.get('homie_score', 0)}/10
**PyMasters Score:** {item.get('pymasters_score', 0)}/10

### Context
This item scored high for Homie integration. It could also make a great PyMasters tutorial
teaching developers how to build similar capabilities.

### Opportunity
{item.get('opportunity', 'N/A')}

### Tutorial Suggestion
- Teach readers how to implement this technique in Python
- Show how it can be integrated into a local AI assistant
- Include practical code examples and best practices
- Reference the Homie project as a real-world example

### Description
{item.get('description', 'N/A')[:500]}

---
*Cross-pollination issue created by the PyMasters AI Intelligence Pipeline.*
"""

    try:
        _ensure_label(PYMASTERS_REPO)
        result = _gh(
            "issue", "create",
            "--repo", PYMASTERS_REPO,
            "--title", title,
            "--body", body,
            "--label", "pipeline-generated",
        )
        if result.returncode == 0:
            url = result.stdout.strip()
            log.info(f"Created cross-pollination issue (PyMasters): {url}")
            return {"title": title, "url": url, "type": "cross_homie_to_pymasters", "item": item}
        else:
            log.error(f"Failed to create PyMasters cross-pollination issue: {result.stderr}")
    except Exception as exc:
        log.error(f"Error creating cross-pollination issue: {exc}")

    return None


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def cross_pollinate(items: list[dict]) -> list[dict]:
    """Create cross-pollination issues between Homie and PyMasters.

    Items that score high for BOTH products get issues on both repos.
    Items scoring high for one product get a suggestion on the other.

    Returns list of created issues.
    """
    results: list[dict] = []

    # Items relevant to both products
    both_items = [
        item for item in items
        if item.get("product") == "both"
        and item.get("homie_score", 0) >= RELEVANCE_THRESHOLD_HOMIE
        and item.get("pymasters_score", 0) >= RELEVANCE_THRESHOLD_PYMASTERS
    ]

    # Items primarily for PyMasters but potentially useful for Homie
    pymasters_to_homie = [
        item for item in items
        if item.get("product") == "pymasters"
        and item.get("pymasters_score", 0) >= RELEVANCE_THRESHOLD_PYMASTERS
        and item.get("homie_score", 0) >= 4  # moderate Homie relevance
    ]

    # Items primarily for Homie but potentially good tutorial material
    homie_to_pymasters = [
        item for item in items
        if item.get("product") == "homie"
        and item.get("homie_score", 0) >= RELEVANCE_THRESHOLD_HOMIE
        and item.get("pymasters_score", 0) >= 4  # moderate PyMasters relevance
    ]

    candidates = both_items + pymasters_to_homie + homie_to_pymasters
    if not candidates:
        log.info("No cross-pollination candidates found.")
        return results

    log.info(f"Found {len(candidates)} cross-pollination candidates "
             f"(both={len(both_items)}, pm->homie={len(pymasters_to_homie)}, "
             f"homie->pm={len(homie_to_pymasters)}).")

    homie_existing = _get_existing_titles(HOMIE_REPO)
    pymasters_existing = _get_existing_titles(PYMASTERS_REPO)

    # Process "both" items — create issues on both repos
    for item in both_items[:3]:  # cap at 3
        issue = _create_homie_issue_from_pymasters(item, homie_existing)
        if issue:
            results.append(issue)
            homie_existing.add(issue["title"])

        issue = _create_pymasters_issue_from_homie(item, pymasters_existing)
        if issue:
            results.append(issue)
            pymasters_existing.add(issue["title"])

    # PyMasters discoveries -> Homie suggestions
    for item in pymasters_to_homie[:2]:  # cap at 2
        issue = _create_homie_issue_from_pymasters(item, homie_existing)
        if issue:
            results.append(issue)
            homie_existing.add(issue["title"])

    # Homie discoveries -> PyMasters tutorial suggestions
    for item in homie_to_pymasters[:2]:  # cap at 2
        issue = _create_pymasters_issue_from_homie(item, pymasters_existing)
        if issue:
            results.append(issue)
            pymasters_existing.add(issue["title"])

    log.info(f"Cross-pollination complete: {len(results)} issues created.")
    return results
