"""Generate daily digest report."""

import os
from datetime import datetime
from pipeline.config import REPORTS_DIR
from pipeline.utils.logger import get_logger

log = get_logger("actor.digest")


def generate_digest(
    items: list[dict],
    issues_created: list[dict],
    collection_stats: dict,
) -> str:
    """Generate a markdown daily digest and save it to reports/."""
    today = datetime.now().strftime("%Y-%m-%d")
    top_items = items[:10]

    lines = [
        f"# PyMasters AI Intelligence Digest - {today}",
        "",
        "## Collection Summary",
        "",
        f"| Source | Items Collected |",
        f"|--------|----------------|",
    ]

    for source, count in sorted(collection_stats.items()):
        lines.append(f"| {source} | {count} |")

    lines.append(f"| **Total** | **{sum(collection_stats.values())}** |")
    lines.append("")

    # Top discoveries
    lines.append("## Top 10 Discoveries")
    lines.append("")

    for i, item in enumerate(top_items, 1):
        score = item.get("relevance_score", 0)
        product = item.get("product", "neither")
        source = item.get("source", "unknown")
        lines.append(f"### {i}. {item.get('title', 'Unknown')}")
        lines.append(f"- **Source:** {source}")
        lines.append(f"- **Score:** {score}/10 ({product})")
        lines.append(f"- **URL:** {item.get('url', 'N/A')}")
        lines.append(f"- **Opportunity:** {item.get('opportunity', 'N/A')}")
        desc = item.get("description", "")[:200]
        if desc:
            lines.append(f"- **Description:** {desc}")
        lines.append("")

    # Actions taken
    lines.append("## Actions Taken")
    lines.append("")

    if issues_created:
        lines.append(f"### GitHub Issues Created ({len(issues_created)})")
        lines.append("")
        for issue in issues_created:
            lines.append(f"- [{issue['title']}]({issue.get('url', '#')})")
        lines.append("")
    else:
        lines.append("No GitHub issues created today.")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append(f"*Generated by PyMasters AI Intelligence Pipeline on {today}*")
    lines.append("")

    report_content = "\n".join(lines)

    # Save to file
    os.makedirs(REPORTS_DIR, exist_ok=True)
    report_path = os.path.join(REPORTS_DIR, f"{today}.md")
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report_content)

    log.info(f"Digest saved to {report_path}")
    return report_path
