"""Create GitHub issues for high-scoring Homie items."""

import subprocess
import json
from pipeline.config import HOMIE_REPO, RELEVANCE_THRESHOLD_HOMIE, MAX_ISSUES_PER_DAY
from pipeline.utils.logger import get_logger

log = get_logger("actor.github_issues")


def _get_existing_pipeline_issues() -> set[str]:
    """Get titles of existing pipeline-generated issues to avoid duplicates."""
    try:
        result = subprocess.run(
            [
                "gh", "issue", "list",
                "--repo", HOMIE_REPO,
                "--label", "pipeline-generated",
                "--state", "all",
                "--limit", "100",
                "--json", "title",
            ],
            capture_output=True,
            text=True,
            timeout=30,
        )
        if result.returncode == 0:
            issues = json.loads(result.stdout)
            return {issue["title"] for issue in issues}
    except Exception as e:
        log.warning(f"Could not fetch existing issues: {e}")

    return set()


def create_issues(items: list[dict]) -> list[dict]:
    """Create GitHub issues for high-scoring Homie items. Returns list of created issues."""
    created = []

    # Filter to Homie-relevant items above threshold
    candidates = [
        item for item in items
        if item.get("homie_score", 0) >= RELEVANCE_THRESHOLD_HOMIE
        and item.get("product") in ("homie", "both")
    ]

    if not candidates:
        log.info("No items above Homie relevance threshold.")
        return created

    # Check existing issues for deduplication
    existing_titles = _get_existing_pipeline_issues()

    issues_created = 0
    for item in candidates:
        if issues_created >= MAX_ISSUES_PER_DAY:
            log.info(f"Reached max issues per day ({MAX_ISSUES_PER_DAY}).")
            break

        title = f"[Pipeline] {item.get('opportunity', item.get('title', 'Unknown'))}"

        # Skip if a similar issue already exists
        if title in existing_titles:
            log.info(f"Skipping duplicate issue: {title}")
            continue

        body = f"""## Auto-generated by PyMasters AI Intelligence Pipeline

**Source:** {item.get('source', 'unknown')}
**Original:** [{item.get('title', '')}]({item.get('url', '')})
**Homie Score:** {item.get('homie_score', 0)}/10
**PyMasters Score:** {item.get('pymasters_score', 0)}/10

### Opportunity
{item.get('opportunity', 'N/A')}

### Description
{item.get('description', 'N/A')[:500]}

### Suggested Implementation
Based on the relevance analysis, this item could be integrated into Homie as described above.
Please evaluate feasibility and priority.

---
*This issue was automatically created by the daily AI intelligence pipeline.*"""

        try:
            # Ensure the label exists first
            subprocess.run(
                [
                    "gh", "label", "create", "pipeline-generated",
                    "--repo", HOMIE_REPO,
                    "--color", "0E8A16",
                    "--description", "Auto-generated by AI pipeline",
                    "--force",
                ],
                capture_output=True,
                text=True,
                timeout=15,
            )

            result = subprocess.run(
                [
                    "gh", "issue", "create",
                    "--repo", HOMIE_REPO,
                    "--title", title,
                    "--body", body,
                    "--label", "pipeline-generated",
                ],
                capture_output=True,
                text=True,
                timeout=30,
            )

            if result.returncode == 0:
                issue_url = result.stdout.strip()
                log.info(f"Created issue: {issue_url}")
                created.append({
                    "title": title,
                    "url": issue_url,
                    "item": item,
                })
                issues_created += 1
            else:
                log.error(f"Failed to create issue '{title}': {result.stderr}")
        except Exception as e:
            log.error(f"Error creating issue '{title}': {e}")

    return created
