"""HuggingFace Publisher — create Spaces and dataset cards from pipeline discoveries."""

import os
import tempfile
from datetime import datetime
from huggingface_hub import HfApi, create_repo, upload_file
from pipeline.utils.logger import get_logger

log = get_logger("actor.hf_publisher")

HF_NAMESPACE = "Muthu88"
PYMASTERS_URL = "https://pymasters.net"
HOMIE_URL = "https://heyhomie.app"


def _build_readme(title: str, description: str, extra_content: str = "") -> str:
    """Build a README.md with branding links."""
    return f"""---
title: {title}
emoji: "\U0001f680"
colorFrom: blue
colorTo: purple
sdk: gradio
sdk_version: "4.44.0"
app_file: app.py
pinned: false
---

# {title}

{description}

{extra_content}

---

**Built by [PyMasters]({PYMASTERS_URL})** | Try [Homie - Local AI Assistant]({HOMIE_URL})

*Auto-generated by the PyMasters AI Intelligence Pipeline on {datetime.now().strftime("%Y-%m-%d")}*
"""


def publish_space(title: str, description: str, code: str) -> dict:
    """Create a Gradio-based HuggingFace Space.

    Args:
        title: Display title for the Space.
        description: Short description of what the demo does.
        code: Python source code for app.py (must be a valid Gradio app).

    Returns:
        dict with keys: repo_id, url, status.
    """
    # Sanitize title into a repo-safe slug
    slug = title.lower().replace(" ", "-")
    slug = "".join(c for c in slug if c.isalnum() or c == "-")[:60]
    repo_id = f"{HF_NAMESPACE}/{slug}"

    log.info(f"Publishing HF Space: {repo_id}")

    try:
        api = HfApi()

        # Create the Space repo (Gradio SDK)
        create_repo(
            repo_id=repo_id,
            repo_type="space",
            space_sdk="gradio",
            exist_ok=True,
        )

        # Upload README.md
        readme_content = _build_readme(title, description)
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".md", delete=False, encoding="utf-8"
        ) as f:
            f.write(readme_content)
            readme_path = f.name

        try:
            upload_file(
                path_or_fileobj=readme_path,
                path_in_repo="README.md",
                repo_id=repo_id,
                repo_type="space",
            )
        finally:
            os.unlink(readme_path)

        # Upload app.py
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".py", delete=False, encoding="utf-8"
        ) as f:
            f.write(code)
            app_path = f.name

        try:
            upload_file(
                path_or_fileobj=app_path,
                path_in_repo="app.py",
                repo_id=repo_id,
                repo_type="space",
            )
        finally:
            os.unlink(app_path)

        # Upload requirements.txt with gradio pinned
        requirements = "gradio>=4.0.0\n"
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".txt", delete=False, encoding="utf-8"
        ) as f:
            f.write(requirements)
            req_path = f.name

        try:
            upload_file(
                path_or_fileobj=req_path,
                path_in_repo="requirements.txt",
                repo_id=repo_id,
                repo_type="space",
            )
        finally:
            os.unlink(req_path)

        url = f"https://huggingface.co/spaces/{repo_id}"
        log.info(f"Space published: {url}")
        return {"repo_id": repo_id, "url": url, "status": "published"}

    except Exception as e:
        log.error(f"Failed to publish Space '{repo_id}': {e}")
        return {"repo_id": repo_id, "url": "", "status": f"failed: {e}"}


def publish_dataset_card(name: str, description: str, data_url: str) -> dict:
    """Create a dataset repository with a card linking back to pymasters.net.

    Args:
        name: Dataset name (will be slugified).
        description: What the dataset contains.
        data_url: URL where the actual data can be found.

    Returns:
        dict with keys: repo_id, url, status.
    """
    slug = name.lower().replace(" ", "-")
    slug = "".join(c for c in slug if c.isalnum() or c == "-")[:60]
    repo_id = f"{HF_NAMESPACE}/{slug}"

    log.info(f"Publishing dataset card: {repo_id}")

    try:
        api = HfApi()

        create_repo(
            repo_id=repo_id,
            repo_type="dataset",
            exist_ok=True,
        )

        card_content = f"""---
dataset_info:
  name: {name}
  description: {description}
license: mit
---

# {name}

{description}

## Data Source

The data for this dataset is available at: [{data_url}]({data_url})

## About

This dataset was curated as part of the [PyMasters]({PYMASTERS_URL}) AI intelligence pipeline.
PyMasters provides tutorials, courses, and learning paths for Python developers working with AI/ML.

Check out [Homie]({HOMIE_URL}) — a cross-platform local AI assistant that runs on your device.

---

*Auto-generated by the PyMasters AI Intelligence Pipeline on {datetime.now().strftime("%Y-%m-%d")}*
"""

        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".md", delete=False, encoding="utf-8"
        ) as f:
            f.write(card_content)
            card_path = f.name

        try:
            upload_file(
                path_or_fileobj=card_path,
                path_in_repo="README.md",
                repo_id=repo_id,
                repo_type="dataset",
            )
        finally:
            os.unlink(card_path)

        url = f"https://huggingface.co/datasets/{repo_id}"
        log.info(f"Dataset card published: {url}")
        return {"repo_id": repo_id, "url": url, "status": "published"}

    except Exception as e:
        log.error(f"Failed to publish dataset card '{repo_id}': {e}")
        return {"repo_id": repo_id, "url": "", "status": f"failed: {e}"}


def maybe_publish_space_for_item(item: dict) -> dict | None:
    """Generate a simple Gradio demo Space for a high-scoring pipeline item.

    This creates a minimal informational Space that showcases the discovery.
    Returns the publish result or None if skipped.
    """
    title = item.get("title", "AI Discovery")
    description = item.get("description", "")[:300]
    opportunity = item.get("opportunity", "")
    source_url = item.get("url", "")
    score = item.get("relevance_score", 0)

    space_title = f"pymasters-{title[:40]}".replace(" ", "-").lower()
    space_title = "".join(c for c in space_title if c.isalnum() or c == "-")

    # Generate a simple Gradio app that presents the discovery
    code = f'''"""Auto-generated PyMasters AI Discovery Space."""

import gradio as gr

TITLE = """{title}"""
DESCRIPTION = """{description.replace('"', "'")}"""
OPPORTUNITY = """{opportunity.replace('"', "'")}"""
SOURCE_URL = "{source_url}"
SCORE = {score}

def show_info():
    return f"""## {{TITLE}}

**Relevance Score:** {{SCORE}}/10

### Description
{{DESCRIPTION}}

### Opportunity
{{OPPORTUNITY}}

### Source
[Original Link]({{SOURCE_URL}})

---
Visit [pymasters.net](https://pymasters.net) for AI tutorials and learning paths.
Try [Homie](https://heyhomie.app) - your local AI assistant.
"""

with gr.Blocks(title=TITLE) as demo:
    gr.Markdown(f"# {{TITLE}}")
    gr.Markdown("*Discovered by the PyMasters AI Intelligence Pipeline*")
    output = gr.Markdown(value=show_info())

demo.launch()
'''

    return publish_space(space_title, f"AI Discovery: {title}", code)
