"""Auto-generate Homie improvements based on pipeline discoveries.

Handles three categories:
1. Plugin opportunities  - generate plugin code and create PRs on MuthuGsubramanian/Homie
2. Model recommendations - create issues when new GGUF models are trending
3. Capability improvements - create detailed issues with implementation suggestions
"""

import json
import os
import subprocess
import tempfile
import textwrap
from pathlib import Path

from anthropic import Anthropic

from pipeline.config import HOMIE_REPO, RELEVANCE_THRESHOLD_HOMIE
from pipeline.utils.logger import get_logger

log = get_logger("actor.homie_evolution")

MAX_PRS_PER_RUN = 2

# Path to the Homie repo (for reading plugin structure).  Resolved relative
# to this file's location so it works in CI and locally.
_HOMIE_SRC = Path(os.getenv(
    "HOMIE_SRC",
    str(Path(__file__).resolve().parents[2].parent / "Homie" / "src" / "homie"),
))

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _gh(*args: str, timeout: int = 30) -> subprocess.CompletedProcess:
    """Run a ``gh`` CLI command and return the result."""
    return subprocess.run(
        ["gh", *args],
        capture_output=True,
        text=True,
        timeout=timeout,
    )


def _ensure_label() -> None:
    """Ensure the pipeline-generated label exists on the Homie repo."""
    _gh(
        "label", "create", "pipeline-generated",
        "--repo", HOMIE_REPO,
        "--color", "0E8A16",
        "--description", "Auto-generated by AI pipeline",
        "--force",
    )


def _get_existing_titles() -> set[str]:
    """Return titles of existing pipeline-generated issues and PRs."""
    titles: set[str] = set()
    for state in ("open", "closed"):
        try:
            result = _gh(
                "issue", "list",
                "--repo", HOMIE_REPO,
                "--label", "pipeline-generated",
                "--state", state,
                "--limit", "100",
                "--json", "title",
            )
            if result.returncode == 0:
                for entry in json.loads(result.stdout):
                    titles.add(entry["title"])
        except Exception as exc:
            log.warning(f"Could not fetch existing issues ({state}): {exc}")

    # Also check open PRs
    try:
        result = _gh(
            "pr", "list",
            "--repo", HOMIE_REPO,
            "--label", "pipeline-generated",
            "--state", "all",
            "--limit", "100",
            "--json", "title",
        )
        if result.returncode == 0:
            for entry in json.loads(result.stdout):
                titles.add(entry["title"])
    except Exception as exc:
        log.warning(f"Could not fetch existing PRs: {exc}")

    return titles


def _read_homie_source_context() -> str:
    """Read key Homie source files to give Claude context about the codebase."""
    context_parts: list[str] = []
    files_to_read = [
        _HOMIE_SRC / "__init__.py",
        _HOMIE_SRC / "config.py",
        _HOMIE_SRC / "homie.py",
    ]
    # Also scan for any existing plugin-like files
    if _HOMIE_SRC.exists():
        for py_file in sorted(_HOMIE_SRC.rglob("*.py")):
            rel = py_file.relative_to(_HOMIE_SRC)
            # Skip __pycache__
            if "__pycache__" in str(rel):
                continue
            files_to_read.append(py_file)

    seen: set[str] = set()
    for fpath in files_to_read:
        key = str(fpath.resolve())
        if key in seen or not fpath.exists():
            continue
        seen.add(key)
        try:
            content = fpath.read_text(encoding="utf-8", errors="replace")
            # Truncate large files
            if len(content) > 3000:
                content = content[:3000] + "\n# ... (truncated)"
            context_parts.append(f"### {fpath.relative_to(_HOMIE_SRC.parent)}\n```python\n{content}\n```")
        except Exception:
            pass

    return "\n\n".join(context_parts[:15])  # cap at 15 files


# ---------------------------------------------------------------------------
# Plugin generation
# ---------------------------------------------------------------------------

_PLUGIN_GEN_SYSTEM = textwrap.dedent("""\
    You are a senior Python developer contributing to Homie, a cross-platform local AI assistant.
    Homie uses: llama.cpp (GGUF inference), ChromaDB (RAG), Whisper (STT), Piper (TTS).
    It is a LOCAL desktop/mobile app, NOT a web service.

    When asked to generate a plugin, produce a SINGLE Python file that:
    - Has a module-level docstring explaining the plugin
    - Contains a class inheriting from a base if one exists, or a standalone class
    - Includes an ``activate()`` / ``deactivate()`` pair or ``register()`` function
    - Has clear type hints and docstrings
    - Is safe to run locally (no network calls unless opt-in)
    - Follows existing Homie code conventions shown in the context
""")


def _generate_plugin_code(item: dict, homie_context: str) -> tuple[str, str, str]:
    """Use Claude to generate plugin code. Returns (filename, code, description)."""
    client = Anthropic()

    prompt = textwrap.dedent(f"""\
        ## Task
        Generate a Homie plugin based on this pipeline discovery:

        **Title:** {item.get('title', '')}
        **Source:** {item.get('source', '')}
        **URL:** {item.get('url', '')}
        **Opportunity:** {item.get('opportunity', '')}
        **Description:** {item.get('description', '')[:500]}

        ## Existing Homie Codebase Context
        {homie_context}

        ## Output Format
        Respond with ONLY a JSON object (no markdown fences):
        {{
            "filename": "plugin_name.py",
            "code": "... full Python source ...",
            "description": "A one-paragraph description of what this plugin does and how it integrates with Homie."
        }}
    """)

    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=4096,
        system=_PLUGIN_GEN_SYSTEM,
        messages=[{"role": "user", "content": prompt}],
    )

    text = response.content[0].text.strip()
    # Handle markdown code blocks
    if text.startswith("```"):
        lines = text.split("\n")
        text = "\n".join(lines[1:-1])

    data = json.loads(text)
    return data["filename"], data["code"], data["description"]


def _create_plugin_pr(item: dict, homie_context: str, existing_titles: set[str]) -> dict | None:
    """Generate a plugin and open a PR on the Homie repo. Returns PR info or None."""
    title = f"[Pipeline] Add plugin: {item.get('opportunity', item.get('title', ''))}"
    if title in existing_titles:
        log.info(f"Skipping duplicate PR: {title}")
        return None

    log.info(f"Generating plugin for: {item.get('title', '')}")
    try:
        filename, code, description = _generate_plugin_code(item, homie_context)
    except Exception as exc:
        log.error(f"Plugin code generation failed: {exc}")
        return None

    # Sanitize filename
    filename = filename.replace("/", "_").replace("\\", "_")
    if not filename.endswith(".py"):
        filename += ".py"

    branch_name = f"pipeline/plugin-{filename.replace('.py', '').replace('_', '-')}"

    # Use a temporary directory to stage the PR
    with tempfile.TemporaryDirectory() as tmpdir:
        try:
            # Clone the repo shallowly
            clone_result = subprocess.run(
                ["gh", "repo", "clone", HOMIE_REPO, tmpdir, "--", "--depth=1"],
                capture_output=True, text=True, timeout=60,
            )
            if clone_result.returncode != 0:
                log.error(f"Clone failed: {clone_result.stderr}")
                return None

            repo_dir = Path(tmpdir)

            # Create branch
            subprocess.run(
                ["git", "checkout", "-b", branch_name],
                cwd=repo_dir, capture_output=True, text=True, timeout=10,
            )

            # Write plugin file
            plugin_dir = repo_dir / "src" / "homie" / "plugins"
            plugin_dir.mkdir(parents=True, exist_ok=True)

            # Ensure __init__.py exists
            init_file = plugin_dir / "__init__.py"
            if not init_file.exists():
                init_file.write_text('"""Homie plugins package."""\n', encoding="utf-8")

            plugin_path = plugin_dir / filename
            plugin_path.write_text(code, encoding="utf-8")

            # Commit
            subprocess.run(["git", "add", "."], cwd=repo_dir, capture_output=True, text=True)
            commit_msg = f"feat(plugin): add {filename.replace('.py', '')} plugin\n\nGenerated by PyMasters AI Intelligence Pipeline.\nSource: {item.get('url', 'N/A')}"
            subprocess.run(
                ["git", "commit", "-m", commit_msg],
                cwd=repo_dir, capture_output=True, text=True, timeout=15,
            )

            # Push
            push_result = subprocess.run(
                ["git", "push", "origin", branch_name],
                cwd=repo_dir, capture_output=True, text=True, timeout=60,
            )
            if push_result.returncode != 0:
                log.error(f"Push failed: {push_result.stderr}")
                return None

            # Create PR
            body = textwrap.dedent(f"""\
                ## Auto-generated by PyMasters AI Intelligence Pipeline

                **Source:** {item.get('source', 'unknown')}
                **Original:** [{item.get('title', '')}]({item.get('url', '')})
                **Homie Score:** {item.get('homie_score', 0)}/10

                ### What this plugin does
                {description}

                ### Plugin file
                `src/homie/plugins/{filename}`

                ### Review checklist
                - [ ] Code quality and safety review
                - [ ] Test locally
                - [ ] Check for security concerns
                - [ ] Verify integration with Homie config

                ---
                *This PR was automatically created by the daily AI intelligence pipeline.*
            """)

            pr_result = subprocess.run(
                [
                    "gh", "pr", "create",
                    "--repo", HOMIE_REPO,
                    "--head", branch_name,
                    "--title", title,
                    "--body", body,
                    "--label", "pipeline-generated",
                ],
                cwd=repo_dir,
                capture_output=True, text=True, timeout=30,
            )

            if pr_result.returncode == 0:
                pr_url = pr_result.stdout.strip()
                log.info(f"Created PR: {pr_url}")
                return {"title": title, "url": pr_url, "type": "plugin_pr", "item": item}
            else:
                log.error(f"PR creation failed: {pr_result.stderr}")
                return None

        except Exception as exc:
            log.error(f"Plugin PR workflow failed: {exc}")
            return None


# ---------------------------------------------------------------------------
# Model recommendation issues
# ---------------------------------------------------------------------------

def _create_model_issue(item: dict, existing_titles: set[str]) -> dict | None:
    """Create a GitHub issue recommending evaluation of a trending GGUF model."""
    title = f"[Pipeline] Evaluate model: {item.get('title', 'Unknown')}"
    if title in existing_titles:
        log.info(f"Skipping duplicate model issue: {title}")
        return None

    body = textwrap.dedent(f"""\
        ## Auto-generated by PyMasters AI Intelligence Pipeline

        **Source:** {item.get('source', 'unknown')}
        **Original:** [{item.get('title', '')}]({item.get('url', '')})
        **Homie Score:** {item.get('homie_score', 0)}/10

        ### Model Recommendation
        {item.get('opportunity', 'N/A')}

        ### Description
        {item.get('description', 'N/A')[:800]}

        ### Suggested Evaluation Steps
        1. Download the GGUF variant (Q4_K_M or Q5_K_M recommended)
        2. Test inference speed on target hardware
        3. Compare quality against current default model
        4. Update `homie.config.yaml` if the model is an improvement
        5. Update `model_evolution` config if applicable

        ### Current Homie Model Config
        - Backend: gguf
        - Context length: 65536
        - Current model path configured in `homie.config.yaml`

        ---
        *This issue was automatically created by the daily AI intelligence pipeline.*
    """)

    try:
        _ensure_label()
        result = _gh(
            "issue", "create",
            "--repo", HOMIE_REPO,
            "--title", title,
            "--body", body,
            "--label", "pipeline-generated",
        )
        if result.returncode == 0:
            url = result.stdout.strip()
            log.info(f"Created model issue: {url}")
            return {"title": title, "url": url, "type": "model_issue", "item": item}
        else:
            log.error(f"Model issue creation failed: {result.stderr}")
    except Exception as exc:
        log.error(f"Error creating model issue: {exc}")

    return None


# ---------------------------------------------------------------------------
# Capability improvement issues
# ---------------------------------------------------------------------------

def _create_capability_issue(item: dict, existing_titles: set[str]) -> dict | None:
    """Create a detailed issue for a capability improvement opportunity."""
    title = f"[Pipeline] {item.get('opportunity', item.get('title', 'Improvement'))}"
    if title in existing_titles:
        log.info(f"Skipping duplicate capability issue: {title}")
        return None

    body = textwrap.dedent(f"""\
        ## Auto-generated by PyMasters AI Intelligence Pipeline

        **Source:** {item.get('source', 'unknown')}
        **Original:** [{item.get('title', '')}]({item.get('url', '')})
        **Homie Score:** {item.get('homie_score', 0)}/10
        **PyMasters Score:** {item.get('pymasters_score', 0)}/10

        ### Opportunity
        {item.get('opportunity', 'N/A')}

        ### Description
        {item.get('description', 'N/A')[:800]}

        ### Implementation Suggestions
        - Review the linked resource for integration patterns
        - Check compatibility with Homie's local-first architecture
        - Consider privacy implications (no data leaves the device)
        - Evaluate resource requirements for target platforms (Windows, Linux, Mac, Android)

        ### Relevant Homie Components
        - `src/homie/config.py` - Configuration management
        - `src/homie/controller/orchestrator.py` - Action orchestration
        - `src/homie/ai_planner.py` - LLM-based planning
        - `homie.config.yaml` - User configuration

        ---
        *This issue was automatically created by the daily AI intelligence pipeline.*
    """)

    try:
        _ensure_label()
        result = _gh(
            "issue", "create",
            "--repo", HOMIE_REPO,
            "--title", title,
            "--body", body,
            "--label", "pipeline-generated",
        )
        if result.returncode == 0:
            url = result.stdout.strip()
            log.info(f"Created capability issue: {url}")
            return {"title": title, "url": url, "type": "capability_issue", "item": item}
        else:
            log.error(f"Capability issue creation failed: {result.stderr}")
    except Exception as exc:
        log.error(f"Error creating capability issue: {exc}")

    return None


# ---------------------------------------------------------------------------
# Classification helpers
# ---------------------------------------------------------------------------

_MODEL_KEYWORDS = {"gguf", "quantized", "model", "llm", "weights", "fine-tune", "finetune"}
_PLUGIN_KEYWORDS = {"plugin", "library", "tool", "integration", "api", "sdk", "package"}


def _classify_item(item: dict) -> str:
    """Classify an item as 'plugin', 'model', or 'capability'."""
    text = " ".join([
        item.get("title", ""),
        item.get("opportunity", ""),
        item.get("description", ""),
    ]).lower()

    # Model recommendations take priority for HuggingFace GGUF items
    if item.get("source") == "huggingface" and "gguf" in text:
        return "model"
    if any(kw in text for kw in _MODEL_KEYWORDS) and item.get("source") == "huggingface":
        return "model"

    # Plugin opportunities
    if any(kw in text for kw in _PLUGIN_KEYWORDS):
        return "plugin"

    return "capability"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def evolve_homie(items: list[dict]) -> list[dict]:
    """Process high-scoring Homie items and create PRs/issues.

    Returns a list of created PRs and issues (dicts with 'title', 'url', 'type').
    """
    candidates = [
        item for item in items
        if item.get("homie_score", 0) >= RELEVANCE_THRESHOLD_HOMIE
        and item.get("product") in ("homie", "both")
    ]

    if not candidates:
        log.info("No Homie evolution candidates found.")
        return []

    log.info(f"Found {len(candidates)} Homie evolution candidates.")
    _ensure_label()

    existing_titles = _get_existing_titles()
    homie_context = _read_homie_source_context()

    results: list[dict] = []
    prs_created = 0

    for item in candidates:
        category = _classify_item(item)
        log.info(f"Processing [{category}]: {item.get('title', '')[:60]}")

        if category == "plugin" and prs_created < MAX_PRS_PER_RUN:
            pr = _create_plugin_pr(item, homie_context, existing_titles)
            if pr:
                results.append(pr)
                existing_titles.add(pr["title"])
                prs_created += 1
        elif category == "model":
            issue = _create_model_issue(item, existing_titles)
            if issue:
                results.append(issue)
                existing_titles.add(issue["title"])
        else:
            issue = _create_capability_issue(item, existing_titles)
            if issue:
                results.append(issue)
                existing_titles.add(issue["title"])

    log.info(f"Homie evolution complete: {len(results)} items created ({prs_created} PRs).")
    return results
