[theme]
base = "dark"
primaryColor = "#22c55e"
backgroundColor = "#09090b"
secondaryBackgroundColor = "#18181b"
textColor = "#a1a1aa"
font = "monospace"

[server]
headless = true

[browser]
gatherUsageStats = false
